"""Add ViolationRecord model

Revision ID: 8be6e339d671
Revises: 
Create Date: 2025-03-22 11:25:11.981810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be6e339d671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_path', sa.String(length=255), nullable=False),
    sa.Column('processed_path', sa.String(length=255), nullable=False),
    sa.Column('total_bikers', sa.Integer(), nullable=True),
    sa.Column('no_helmet', sa.Integer(), nullable=True),
    sa.Column('using_phone', sa.Integer(), nullable=True),
    sa.Column('compliant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_record')
    # ### end Alembic commands ###
